version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aggregator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    # Updated: Run directly from the root
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    # Updated: No need to cd into a folder first
    command: celery -A aggregator_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    # Updated: No need to cd into a folder first
    command: celery -A aggregator_project beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: